# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOjb1YaT81tv_m2FAqGpacdPKXWhcdh1
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

st.set_page_config(
    page_title="Movie Rating Prediction Dashboard",
    page_icon="🎬",
    layout="wide"
)

@st.cache_data
def load_data():
    df = pd.read_csv("movies_cleaned.csv")
    return df

df = load_data()

st.title("🎬 Predicting Movie Audience Ratings")
st.markdown(
    """
    This Streamlit application demonstrates a predictive analytics solution using the Kaggle Movies Dataset.
    The goal is to help movie studios, streaming platforms, and investors estimate audience rating risk using
    production characteristics and early performance indicators.
    """
)

st.sidebar.header("Filters")

if "release_year" in df.columns:
    min_year = int(df["release_year"].min())
    max_year = int(df["release_year"].max())
    year_range = st.sidebar.slider(
        "Release Year Range",
        min_year,
        max_year,
        (min_year, max_year)
    )
    df_filtered = df[
        (df["release_year"] >= year_range[0]) &
        (df["release_year"] <= year_range[1])
    ]
else:
    df_filtered = df.copy()

if "original_language" in df.columns:
    languages = sorted(df_filtered["original_language"].dropna().unique())
    selected_languages = st.sidebar.multiselect(
        "Original Language",
        languages,
        default=languages[:5] if len(languages) > 5 else languages
    )
    if selected_languages:
        df_filtered = df_filtered[df_filtered["original_language"].isin(selected_languages)]

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Executive Overview",
    "Data Explorer",
    "Insights Dashboard",
    "Rating Prediction Tool",
    "Business Recommendations"
])

with tab1:
    st.header("Executive Overview")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Movies Analyzed", f"{len(df_filtered):,}")

    with col2:
        if "vote_average" in df_filtered.columns:
            st.metric("Average Rating", round(df_filtered["vote_average"].mean(), 2))

    with col3:
        if "budget" in df_filtered.columns:
            st.metric("Average Budget", f"${df_filtered['budget'].mean():,.0f}")

    with col4:
        if "revenue" in df_filtered.columns:
            st.metric("Average Revenue", f"${df_filtered['revenue'].mean():,.0f}")

    st.subheader("Business Problem")
    st.write(
        """
        Movie studios and streaming platforms make high-cost decisions before knowing how audiences will respond.
        This project uses predictive analytics to estimate audience ratings earlier in the decision-making process,
        helping decision makers identify potential rating risk and support better planning.
        """
    )

    st.subheader("Research Question")
    st.info(
        "Can a movie’s average audience rating be predicted using production characteristics and early performance indicators?"
    )

    st.subheader("Analytical Approach")
    st.write(
        """
        This project uses a regression-based predictive model. The target variable is audience rating,
        represented by `vote_average`. Predictor variables include budget, revenue, popularity, vote count,
        runtime, release timing, language, genre count, and other engineered features.
        """
    )

with tab2:
    st.header("Data Explorer")

    st.write("Use this section to explore the filtered movie dataset.")

    st.dataframe(df_filtered.head(100), use_container_width=True)

    st.subheader("Dataset Summary")
    st.write(df_filtered.describe(include="all"))

with tab3:
    st.header("Insights Dashboard")

    col1, col2 = st.columns(2)

    with col1:
        if "release_year" in df_filtered.columns and "vote_average" in df_filtered.columns:
            yearly_rating = df_filtered.groupby("release_year", as_index=False)["vote_average"].mean()
            fig = px.line(
                yearly_rating,
                x="release_year",
                y="vote_average",
                title="Average Audience Rating by Release Year"
            )
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        if "runtime" in df_filtered.columns and "vote_average" in df_filtered.columns:
            fig = px.scatter(
                df_filtered,
                x="runtime",
                y="vote_average",
                title="Runtime vs. Audience Rating",
                opacity=0.5
            )
            st.plotly_chart(fig, use_container_width=True)

    col3, col4 = st.columns(2)

    with col3:
        if "budget" in df_filtered.columns and "vote_average" in df_filtered.columns:
            fig = px.scatter(
                df_filtered,
                x="budget",
                y="vote_average",
                title="Budget vs. Audience Rating",
                opacity=0.5
            )
            st.plotly_chart(fig, use_container_width=True)

    with col4:
        if "popularity" in df_filtered.columns and "vote_average" in df_filtered.columns:
            fig = px.scatter(
                df_filtered,
                x="popularity",
                y="vote_average",
                title="Popularity vs. Audience Rating",
                opacity=0.5
            )
            st.plotly_chart(fig, use_container_width=True)

    st.subheader("Key Insight")
    st.success(
        """
        Budget alone is not enough to explain audience rating. Stronger predictive value comes from combining
        production variables with early engagement indicators such as popularity and vote count.
        """
    )

with tab4:
    st.header("Rating Prediction Tool")

    st.write(
        """
        Enter a movie scenario below. The app will estimate the expected audience rating using a regression model
        trained on the available movie data.
        """
    )

    model_features = [
        "log_budget",
        "log_revenue",
        "runtime",
        "release_year",
        "release_month",
        "genre_count",
        "production_company_count",
        "language_count",
        "is_english",
        "has_tagline",
        "log_popularity",
        "log_vote_count"
    ]

    available_features = [col for col in model_features if col in df.columns]

    if "vote_average" in df.columns and len(available_features) >= 3:
        model_data = df[available_features + ["vote_average"]].dropna()

        X = model_data[available_features]
        y = model_data["vote_average"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=474
        )

        model = LinearRegression()
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        col1, col2 = st.columns(2)
        with col1:
            st.metric("Model R²", round(r2, 3))
        with col2:
            st.metric("RMSE", round(rmse, 3))

        st.subheader("Enter Movie Inputs")

        input_values = {}

        for feature in available_features:
            if feature in ["is_english", "has_tagline"]:
                input_values[feature] = st.selectbox(
                    feature,
                    options=[0, 1],
                    format_func=lambda x: "Yes" if x == 1 else "No"
                )
            else:
                default_value = float(df[feature].median())
                input_values[feature] = st.number_input(
                    feature,
                    value=default_value
                )

        if st.button("Predict Audience Rating"):
            input_df = pd.DataFrame([input_values])
            prediction = model.predict(input_df)[0]

            st.subheader("Prediction Result")
            st.metric("Predicted Audience Rating", round(prediction, 2))

            if prediction >= 6.8:
                st.success("Strong expected rating. This movie profile appears relatively favorable.")
            elif prediction >= 5.8:
                st.warning("Moderate expected rating. This movie profile may perform acceptably but has some uncertainty.")
            else:
                st.error("Lower expected rating. This movie profile may carry audience rating risk.")

            st.write(
                """
                A non-technical stakeholder can use this prediction as an early signal, not as a guaranteed outcome.
                The model supports better planning by identifying whether a movie profile appears stronger, moderate,
                or potentially risky based on historical patterns.
                """
            )

    else:
        st.warning(
            """
            The prediction tool needs the required engineered features and `vote_average` column.
            Make sure your cleaned dataset includes the model variables used in your final project.
            """
        )

with tab5:
    st.header("Business Recommendations")

    st.subheader("Decision-Maker Value")
    st.write(
        """
        This solution helps decision makers evaluate movie projects earlier by translating historical movie data
        into a practical prediction and risk-assessment tool. Instead of relying only on intuition, executives can
        compare movie profiles, test assumptions, and identify potential rating risk before making marketing,
        distribution, or investment decisions.
        """
    )

    st.subheader("Recommended Use Cases")
    st.markdown(
        """
        - Compare expected ratings across different movie profiles.
        - Identify movies that may need stronger marketing support.
        - Evaluate how early popularity and engagement indicators relate to audience response.
        - Support greenlighting, distribution, and campaign planning decisions.
        """
    )

    st.subheader("Limitations")
    st.markdown(
        """
        - The model does not perfectly predict audience taste.
        - Vote count and popularity may reflect post-release engagement, so predictions are strongest when early signals are available.
        - External factors such as reviews, actors, franchise strength, and cultural trends may also influence ratings.
        """
    )

    st.subheader("Final Learning")
    st.info(
        """
        The main takeaway is that audience ratings are partially predictable, but no single variable explains them.
        The strongest solution comes from combining business understanding, data preparation, feature engineering,
        model evaluation, and deployment into one accessible decision-support tool.
        """
    )